#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


echo "Running app migrations..."
python -m alembic.config upgrade head

echo "Starting app..."
uvicorn ${API_APP} \
    --host 0.0.0.0 \
    --port ${PORT} --workers 1
