#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset


echo "Starting fastapi app with debugpy support..."

watchmedo auto-restart --recursive -p '*.py' \
    -- python -m debugpy --listen 0.0.0.0:${DEBUG_PORT} \
    -m uvicorn ${API_APP} --host 0.0.0.0 --port ${PORT} --workers 1

echo "FastAPI app running! Debugpy now accepting remote attach from clients..."
