#!/bin/sh

set -o errexit
set -o nounset


# watchmedo auto-restart --recursive -p '*.py' -- \
#     python -m celery --app app.worker worker \
#         --queues main-queue \
#         --events \
#         --logfile celery-worker.log \
#         --loglevel DEBUG \
#         --concurrency=1 \
#         --autoscale=1,1 \
#         --pool solo

watchmedo auto-restart --recursive -p '*.py' -- \
    huey_consumer app.worker.huey -k process -w 4
